Data1.6 <- read.table("js1.6.merge.data")
Data1.7 <- read.table("js1.7.merge.data")
Data1.8.5 <- read.table("js1.8.5.merge.data")
with(Data1.6, t.test(bcov[swarm == 1], bcov[swarm == 0]))
with(Data1.6, t.test(lcov[swarm == 1], lcov[swarm == 0]))
with(Data1.6, t.test(fail[swarm == 1], fail[swarm == 0]))
with(Data1.7, t.test(bcov[swarm == 1], bcov[swarm == 0]))
with(Data1.7, t.test(lcov[swarm == 1], lcov[swarm == 0]))
with(Data1.7, t.test(fail[swarm == 1], fail[swarm == 0]))
with(Data1.8.5, t.test(bcov[swarm == 1], bcov[swarm == 0]))
with(Data1.8.5, t.test(lcov[swarm == 1], lcov[swarm == 0]))
with(Data1.8.5, t.test(fail[swarm == 1], fail[swarm == 0]))